= arch-install
:toc:
:toc-placement!:
:sectanchors:
:sectnums:
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

Installation guide for Arch GNU/Linux with Btrfs, RAID1 and dm-crypt full disk encryption.

toc::[]

== Prerequisites

Download an installation image and copy it to a USB flash drive:

```bash
cp archlinux.iso /dev/disk/by-id/usb-…
sync
reboot
```

Use prepared installation medium to boot into the live environment.

== Connect to the internet:

Ethernet:: Plug in the cable and you should be good to go.
Wi-Fi:: Use `iwctl` to connect to a network.

== Disk setup

=== Setup the partition table

UEFI systems:: Use `gdisk` and create a GPT partition table
BIOS systems:: Use `fdisk` and create a MBR partition table

=== Setup the boot partition

UEFI systems::
.. Create EFI partition of type `00ef` that has at least 1 GB of space
.. Format the partition using FAT32 file system: `mkfs.fat -F 32 -n boot /dev/sdXY`
BIOS systems::
.. Create boot partition of type `0083` that has at least 1 GB of space
.. Format the partition using Ext4 file system: `mkfs.ext4 -L boot /dev/sdXY`

=== Setup the main partitions

Use the rest of unallocated space on all of the remaining drives to create
partitions of type `0083`.

Encrypt all partitions using dm-crypt:

```bash
cp /dev/urandom /dev/sdXY
cryptsetup luksFormat --type luks2 --label main-crypto1 /dev/sdXY
cryptsetup open /dev/disk/by-label/main-crypto1 main1
```

Format all partitions using Btrfs file system and add them to Btrfs RAID1:

```bash
mkfs.btrfs \
    -L main \
    --metadata raid1 \
    --data raid1 \
    /dev/mapper/main[1-X]
```

TIP: RAID1 stores exactly 2 redundant copies of data/metadata, even when there
are more than 2 disks added to the array, so the space utilization is always 50%.
This allows 1 disk to fail without any data loss.
If 3 or 4 redundant copies are desired, use RAID1C3 and RAID1C4 respectively
instead.
For more details on all supported RAID profiles see
https://btrfs.readthedocs.io/en/latest/mkfs.btrfs.html#profiles[man mkfs.btrfs].
Use
https://carfax.org.uk/btrfs-usage/[btrfs disk usage calculator]
to calculate available disk space for a given configuration.

Create Btrfs subvolumes:

```bash
mount --mkdir LABEL=main /mnt
cd /mnt
btrfs subvolume create @
btrfs subvolume create @home
btrfs subvolume create @snapshots
btrfs subvolume create @swap
umount /mnt
```

== Mount the partitions

```bash
mount --mkdir LABEL=main -o noatime,compress=zstd,subvol=@ /mnt
mount --mkdir LABEL=main -o noatime,compress=zstd,subvol=@home /mnt/home
mount --mkdir LABEL=main -o noatime,compress=zstd,subvol=@snapshots /mnt/.snapshots
mount --mkdir LABEL=main -o noatime,compress=zstd,subvol=@swap /mnt/swap
btrfs filesystem mkswapfile --size 16G /mnt/swap/swapfile
swapon /mnt/swap/swapfile
mount --mkdir LABEL=boot /mnt/boot
```

== Bootstrap the system

Install the base packages:

```bash
pacman -Sy archlinux-keyring
pacstrap -K /mnt \
    linux \
    linux-firmware \
    base \
    base-devel \
    btrfs-progs \
    fish \
    neovim \
    tmux
```

Generate `fstab`:

```bash
{
    echo '# <file system> <dir> <type> <options> <dump> <pass>'
    echo 'LABEL=main / btrfs noatime,compress=zstd,subvol=@ 0 0'
    echo 'LABEL=main /home btrfs noatime,compress=zstd,subvol=@home 0 0'
    echo 'LABEL=main /.snapshots btrfs noatime,compress=zstd,subvol=@snapshots 0 0'
    echo 'LABEL=main /swap btrfs noatime,compress=zstd,subvol=@swap 0 0'
    echo '/swap/swapfile none swap defaults 0 0'
    # On UEFI systems
    echo 'LABEL=boot /boot vfat defaults 0 2'
    # On BIOS systems
    echo 'LABEL=boot /boot ext4 defaults 0 2'
} > /mnt/etc/fstab
```

Generate `crypttab.initramfs`:

```bash
{
    echo '# <name> <device> <password> <options>'
    echo 'main1 LABEL=main-crypto1 none discard,no-read-workqueue,no-write-workqueue'
    echo 'main2 LABEL=main-crypto2 none discard,no-read-workqueue,no-write-workqueue'
    # …
} > /mnt/etc/crypttab.initramfs
```

Chroot into the new system:

```bash
arch-chroot /mnt
```

== Generate initramfs

```bash
sed -i -E "s/^(HOOKS).*/\1=(systemd keyboard autodetect microcode modconf kms sd-vconsole sd-encrypt block filesystems fsck)/" /etc/mkinitcpio.conf
mkinitcpio --allpresets
```

== Setup a bootloader

UEFI systems::
+
```bash
bootctl install

{
    echo "default arch"
    echo "editor no"
} >> /boot/loader/loader.conf

{
    echo "title Arch GNU/Linux"
    echo "linux /vmlinuz-linux"
    echo "initrd /initramfs-linux.img"
    echo "options root=LABEL=main rootflags=subvol=@,compress=zstd,noatime rw quiet"
} >> /boot/loader/entries/arch.conf

{
    echo "title Arch GNU/Linux (fallback initramfs)"
    echo "linux /vmlinuz-linux"
    echo "initrd /initramfs-linux-fallback.img"
    echo "options root=LABEL=main rootflags=subvol=@,compress=zstd,noatime rw quiet"
} >> /boot/loader/entries/arch-fallback.conf
```
BIOS systems::
+
```bash
pacman -S grub os-prober
grub-install /dev/sdXY
sed -i -E 's/^(GRUB_TIMEOUT).*/\1=1/' /etc/default/grub
sed -i -E 's/^(GRUB_TIMEOUT_STYLE).*/\1=hidden/' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg
```

== Configure the system

Timezone:

```bash
ln -sf /usr/share/zoneinfo/Europe/Belgrade /etc/localtime
hwclock --systohc
```

Locales:

```bash
sed -i '/^#en_US.UTF-8 UTF-8/s/^#//' /etc/locale.gen
sed -i '/^#en_GB.UTF-8 UTF-8/s/^#//' /etc/locale.gen
sed -i '/^#sr_RS UTF-8/s/^#//' /etc/locale.gen
sed -i '/^#sr_RS@latin UTF-8/s/^#//' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
```

Pacman:

```bash
sed -i '/^#Color/s/^#//' /etc/pacman.conf
sed -i '/^#VerbosePkgLists/s/^#//' /etc/pacman.conf
sed -i -E 's/^(ParallelDownloads).*/\1 = 5/' /etc/pacman.conf
sed -i -E 's/^#(MAKEFLAGS).*/\1="-j$(nproc)"/' /etc/makepkg.conf
```

Network hostname:

```bash
echo librem13 > /etc/hostname
```

Network connection:

NetworkManager::
+
```bash
systemctl enable NetworkManager ModemManager avahi-daemon
```
Systemd-networkd::
+
```bash
systemctl enable systemd-networkd systemd-resolved
rm /etc/resolv.conf
ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
networkctl list
{
    echo '[Match]'
    echo 'Name=en*'
    echo
    echo '[Network]'
    echo 'DHCP=yes'
    echo 'MulticastDNS=true'
} > /etc/systemd/network/ethernet.network
```
Systemd-networkd w/ static IP::
+
```bash
{
    echo '[Match]'
    echo 'Name=en*'
    echo
    echo '[Network]'
    echo 'DHCP=no'
    echo 'MulticastDNS=true'
    echo 'Address=192.168.1.2/24'
    echo 'Gateway=192.168.1.1'
    echo 'DNS=1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com'
    echo 'DNSOverTLS=yes'
    echo 'DNSSEC=true'
} > /etc/systemd/network/ethernet.network
```

User:

```bash
useradd --create-home --groups wheel,docker,uucp bojan
passwd bojan
sed -i '/^# %wheel ALL=(ALL:ALL) ALL$/s/^# //' /etc/sudoers
su bojan
```

== Install packages

Install packages from the official repository:

```bash
sudo pacman -Syuu --needed - < pkglist-XY
```

Install AUR packages:

```bash
git clone "https://aur.archlinux.org/paru.git"
(cd paru && makepkg -si)
paru -Sa - < pkglist-XY-aur
```

Install Rust:

```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
mkdir -p ~/.local/share/bash-completion/completions/
rustup completions bash rustup > ~/.local/share/bash-completion/completions/rustup
rustup completions bash cargo > ~/.local/share/bash-completion/completions/cargo
```

== Enable Systemd services

```bash
sudo systemctl enable btrfs-scrub@-.timer
sudo systemctl enable systemd-boot-update
sudo systemctl enable cups
sudo systemctl enable bluetooth
sudo sed -i -E 's/^#(PermitRootLogin).*/\1 no/' /etc/ssh/sshd_config
sudo sed -i -E 's/^#(PasswordAuthentication).*/\1 no/' /etc/ssh/sshd_config
sudo systemctl enable sshd
sudo useradd --system --create-home syncthing
sudo systemctl enable syncthing@syncthing
sudo systemctl enable docker
sudo systemctl enable gdm
```

== Reboot

Exit the chroot environment and reboot into the newly installed Arch GNU/Linux system.

== License

....
Copyright (C) 2022-2024 Bojan Stipic

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
....
